[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 300 backend.app:app"

[environment]
FLASK_ENV = "production"
SECRET_KEY = "${{RAILWAY_STATIC_URL}}-secret-key-production-2024"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
OPENAI_API_KEY = "${{OPENAI_API_KEY}}"
PYTHONPATH = "/app"
PORT = "${{PORT}}"

[service]
name = "web" 